# Generated by Django 3.2.7 on 2024-02-05 15:50

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Введите имя клиента', max_length=100, verbose_name='Имя Клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Введите время и дату создания заказа', verbose_name='Дата создания')),
                ('order_name', models.CharField(blank=True, help_text='Автоматическая генерация названия заказа', max_length=38, verbose_name='Название заказа')),
                ('description', models.TextField(help_text='Введите описание заказа', verbose_name='Описание заказа')),
                ('phone_number', models.CharField(help_text='Введите телефон клиента в формате: +996xxxxxxxxx', max_length=13, validators=[apps.applications.models.validate_phone_number], verbose_name='Номер телефона клиента')),
                ('email', models.EmailField(help_text='Введите почту клиента', max_length=254, verbose_name='Email клиента')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
