# Generated by Django 5.0.1 on 2024-02-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(help_text='Введите описание заказа', null=True, verbose_name='Описание заказа'),
        ),
    ]
