# Generated by Django 5.0.1 on 2024-02-20 11:03

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='telegram_login',
            field=models.CharField(blank=True, help_text='Ссылка на логин в телеграме', null=True, verbose_name='Ссылка телеграм'),
        ),
        migrations.AddField(
            model_name='application',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Введите телефон клиента в формате (whatsapp): +996xxxxxxxxx', max_length=13, null=True, validators=[apps.applications.models.validate_phone_number], verbose_name='Номер телефона клиента'),
        ),
    ]
