# Generated by Django 5.0.1 on 2024-02-29 11:35

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_telegram_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите телефон клиента в формате: +996xxxxxxxxx', max_length=13, null=True, validators=[apps.applications.models.validate_phone_number], verbose_name='Номер телефона клиента'),
        ),
    ]
