# Generated by Django 5.0.1 on 2024-02-28 10:18

import apps.info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Название города', max_length=100, verbose_name='Название города')),
                ('address', models.CharField(help_text='Улица и дом', max_length=200, verbose_name='Улица и дом')),
                ('phoneNumber', models.CharField(help_text='Номер телефона', max_length=100, verbose_name='Номер телефона')),
                ('whatsApp', models.CharField(help_text='Номер или ссылка на ватсап', max_length=150, verbose_name='Номер или ссылка на ватсап')),
                ('telegram', models.CharField(help_text='Номер или ссылка на телеграм', max_length=150, verbose_name='Номер или ссылка на телеграм')),
                ('instagram', models.CharField(help_text='Ссылка на инстаграм', max_length=150, verbose_name='Ссылка на инстаграм')),
                ('facebook', models.CharField(help_text='Ссылка на фейсбук', max_length=150, verbose_name='Ссылка на фейсбук')),
            ],
            options={
                'verbose_name': 'Информация в футере (нижней части экрана)',
                'verbose_name_plural': 'Информация в футере (нижней части экрана)',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainPageTitle', models.CharField(help_text='Заголовок главного сладйа на главной странице', max_length=200, verbose_name='Заголовок главного сладйа')),
                ('mainPageDescription', models.TextField(verbose_name='Главный слайд - описание')),
                ('mainPageFormImage', models.ImageField(help_text='Изображение внизу главной странциы рядом с формо', upload_to=apps.info.models.upload_to, verbose_name='Изображение внизу главной странциы рядом с формой')),
                ('advantagesOne', models.TextField(verbose_name='Преимущества - первый блок')),
                ('advantagesTwo', models.TextField(verbose_name='Преимущества - второй блок')),
                ('advantagesThree', models.TextField(verbose_name='Преимущества - третий блок')),
                ('renovationWorkTitle', models.CharField(help_text='Заголовок ремонтных работ', max_length=200, verbose_name='Заголовок ремонтных работ')),
                ('renovationWorkDescription', models.TextField(verbose_name='Ремонтные работы - текст')),
                ('renovationWorkImage', models.ImageField(help_text='Изображение ремонтных работ', upload_to=apps.info.models.upload_to, verbose_name='Изображение ремонтных работ')),
                ('serviceStationTitle', models.CharField(help_text='Заголовок станции СТО', max_length=200, verbose_name='Заголовок станции СТО')),
                ('serviceStationDescription', models.TextField(verbose_name='Станции СТО - текст')),
                ('serviceStationImage', models.ImageField(help_text='Изображение станции СТО', upload_to=apps.info.models.upload_to, verbose_name='Изображение станции СТО')),
                ('shippingTitle', models.CharField(help_text='Заголовок перевозки', max_length=200, verbose_name='Заголовок перевозки')),
                ('shippingDescription', models.TextField(verbose_name='Перевозки - текст')),
                ('shippingImage', models.ImageField(help_text='Изображение перевозки', upload_to=apps.info.models.upload_to, verbose_name='Изображение перевозки')),
                ('aboutTitle', models.CharField(help_text='Заголовок О компании', max_length=200, verbose_name='Заголовок О компании')),
                ('aboutDescription', models.TextField(verbose_name='О компании - текст')),
                ('aboutImageOne', models.ImageField(help_text='Изображение в первом блоке О нас', upload_to=apps.info.models.upload_to, verbose_name='Изображение в первом блоке О нас')),
                ('aboutImageTwo', models.ImageField(help_text='Изображение во втором блоке О нас', upload_to=apps.info.models.upload_to, verbose_name='Изображение во втором блоке О нас')),
                ('aboutBlocOneTitle', models.CharField(help_text='Первый блок О нас, заголовок', max_length=200, verbose_name='Первый блок О нас, заголовок')),
                ('aboutBlocTwoTitle', models.CharField(help_text='Второй блок О нас, заголовок', max_length=200, verbose_name='Второй блок О нас, заголовок')),
                ('aboutBlocOneDescription', models.TextField(verbose_name='Первый блок О нас, текст')),
                ('aboutBlocTwoDescription', models.TextField(verbose_name='Второй блок О нас, текст')),
                ('privacy_policy', models.TextField(verbose_name='Политика конфидациальности')),
                ('termsOfUse', models.TextField(verbose_name='Условия использования')),
            ],
            options={
                'verbose_name': 'Информация на сайте',
                'verbose_name_plural': 'Информация на сайте',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainSlider', models.ImageField(help_text='Фотографии для основного слайдера на главной странице', upload_to=apps.info.models.upload_to, verbose_name='Фотографии для основного слайдера на главной странице')),
                ('popularSlider', models.ImageField(help_text='Фотографии для популярной техники', upload_to=apps.info.models.upload_to, verbose_name='Фотографии для популярной техники')),
            ],
            options={
                'verbose_name': 'Фотография для сладейра',
                'verbose_name_plural': 'Фотографии для сладейров',
            },
        ),
    ]
