# Generated by Django 5.0.1 on 2024-02-28 10:39

import apps.info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainSlider', models.ImageField(help_text='Фотографии для основного слайдера на главной странице', upload_to=apps.info.models.upload_to, verbose_name='Фотографии для основного слайдера на главной странице')),
            ],
            options={
                'verbose_name': 'Фотография для главного сладейра',
                'verbose_name_plural': 'Фотографии для главного сладейров',
            },
        ),
        migrations.CreateModel(
            name='popularSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularSlider', models.ImageField(help_text='Фотографии для популярной техники', upload_to=apps.info.models.upload_to, verbose_name='Фотографии для популярной техники')),
            ],
            options={
                'verbose_name': 'Фотография для сладейра популярная техника',
                'verbose_name_plural': 'Фотографии для сладейра популярная техника',
            },
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
