# Generated by Django 3.2.7 on 2024-02-05 15:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название бренда', max_length=40, verbose_name='Название бренда')),
                ('country', models.CharField(help_text='Введите страну бренда', max_length=40, verbose_name='Страна бренда')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='TypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите вид спецтехники', max_length=40, verbose_name='Вид спецтехники')),
            ],
            options={
                'verbose_name': 'Вид спецтехника',
                'verbose_name_plural': 'Виды спецтехники',
            },
        ),
        migrations.CreateModel(
            name='TechModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название спецтехники')),
                ('existence', models.CharField(choices=[('в_наличии', 'В наличии'), ('нет_в_наличии', 'Нет в наличии')], default='В наличии', help_text='Выберите является ли модель в наличии', max_length=40, verbose_name='Наличие модели спецтехники')),
                ('count', models.PositiveIntegerField(default=0, help_text='Введите количество моделей спецтехники', verbose_name='Количество моделей спецтехники')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость модели спецтехники', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена модели спецтехники')),
                ('year', models.IntegerField(help_text='Введите год создания детали', validators=[django.core.validators.MinValueValidator(1958, message='Год должен являться четырхзначным числом'), django.core.validators.MaxValueValidator(2027, message='Год должен являться четырхзначным числом')], verbose_name='Год создания спецтехники')),
                ('description', models.TextField(help_text='Введите описание модели спецтехники', verbose_name='Описание модели спецтехники')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, default='backend/src/media/photos/photo_2024-01-26_17-06-09.jpg', force_format='JPEG', help_text='Загрузите изображение спецтехники', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to='photos/', verbose_name='Фото спецтехники')),
                ('video', models.URLField(blank=True, default='www.youtube.com', help_text='Загрузите видео спецтехники', null=True, verbose_name='Ссылка на видео со спецтехникой')),
                ('brand', models.ForeignKey(help_text='Введите бренд спецтехники', on_delete=django.db.models.deletion.CASCADE, to='techmodel.brand', verbose_name='Название бренда')),
                ('type_name', models.ForeignKey(help_text='Введите вид спецтехники', on_delete=django.db.models.deletion.CASCADE, to='techmodel.typename', verbose_name='Вид спецтехники')),
            ],
            options={
                'verbose_name': 'Модель спецтехники',
                'verbose_name_plural': 'Модели спецтехники',
            },
        ),
    ]
