# Generated by Django 3.2.7 on 2024-02-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techmodel',
            name='additional',
            field=models.TextField(blank=True, help_text='Введите дополнение к деталю', null=True, verbose_name='Дополнительное'),
        ),
        migrations.AddField(
            model_name='techmodel',
            name='characteristic',
            field=models.TextField(blank=True, help_text='Введите характеристику детали', null=True, verbose_name='Характеристика детали'),
        ),
    ]
