# Generated by Django 5.0.1 on 2024-02-07 18:55

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmodel', '0002_auto_20240205_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTechModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='backend/src/media/photos/photo_2024-01-26_17-06-09.jpg', force_format='JPEG', help_text='Загрузите изображение спецтехники', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to='photos/', verbose_name='Фото спецтехники')),
                ('tech_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_techmodels', to='techmodel.techmodel', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Картинка Спецтехники',
                'verbose_name_plural': 'Картинки Спецтехники',
            },
        ),
        migrations.CreateModel(
            name='VideoTechModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, default='www.youtube.com', help_text='Загрузите видео спецтехники', null=True, verbose_name='Ссылка на видео со спецтехникой')),
                ('tech_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_techmodels', to='techmodel.techmodel', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Видео Спецтехники',
                'verbose_name_plural': 'Видео Спецтехники',
            },
        ),
    ]
