# Generated by Django 5.0.1 on 2024-02-11 01:07

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmodel', '0003_imagetechmodel_videotechmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetechmodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Загрузите изображение спецтехники', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to='photos/', verbose_name='Фото спецтехники'),
        ),
        migrations.AlterField(
            model_name='techmodel',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Загрузите изображение спецтехники', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to='photos/', verbose_name='Фото спецтехники'),
        ),
        migrations.AlterField(
            model_name='techmodel',
            name='video',
            field=models.URLField(blank=True, help_text='Загрузите видео спецтехники', null=True, verbose_name='Ссылка на видео со спецтехникой'),
        ),
        migrations.AlterField(
            model_name='videotechmodel',
            name='video',
            field=models.URLField(blank=True, help_text='Загрузите видео спецтехники', null=True, verbose_name='Ссылка на видео со спецтехникой'),
        ),
    ]
