# Generated by Django 5.0.1 on 2024-02-13 16:07

import apps.techmodel.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techmodel', '0004_alter_imagetechmodel_image_alter_techmodel_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetechmodel',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Загрузите изображение спецтехники', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to=apps.techmodel.models.upload_to_image, verbose_name='Фото спецтехники'),
        ),
        migrations.AlterField(
            model_name='techmodel',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Загрузите изображение спецтехники', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to=apps.techmodel.models.upload_to, verbose_name='Фото спецтехники'),
        ),
    ]
