# Generated by Django 5.0.1 on 2024-02-11 01:07

import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpareParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название детали', max_length=40, verbose_name='Название детали')),
                ('existence', models.CharField(choices=[('в_наличии', 'В наличии'), ('нет_в_наличии', 'Нет в наличии')], default='В наличии', help_text='Выберите является ли деталь в наличии', max_length=40, verbose_name='Наличие детали')),
                ('count', models.PositiveIntegerField(default=0, help_text='Введите количество деталий', verbose_name='Количество деталей')),
                ('price', models.DecimalField(decimal_places=2, help_text='Введите стоимость детали', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена детали')),
                ('year', models.IntegerField(help_text='Введите год создания детали', validators=[django.core.validators.MinValueValidator(1958, message='Год должен являться четырхзначным числом'), django.core.validators.MaxValueValidator(2027, message='Год должен являться четырхзначным числом')], verbose_name='Год создания детали')),
                ('description', models.TextField(help_text='Введите описание детали', verbose_name='Описание детали')),
                ('characteristic', models.TextField(blank=True, help_text='Введите характеристику детали', null=True, verbose_name='Характеристика детали')),
                ('additional', models.TextField(blank=True, help_text='Введите дополнение к деталю', null=True, verbose_name='Дополнительное')),
                ('photo', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Загрузите изображение детали', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to='photos/', verbose_name='Картинка детали')),
                ('video', models.URLField(blank=True, help_text='Введите ссылку на видео детали', null=True, verbose_name='Ссылка на видео детали')),
            ],
            options={
                'verbose_name': 'Детали',
                'verbose_name_plural': 'Детали',
            },
        ),
        migrations.CreateModel(
            name='ImageSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Загрузите изображение детали', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to='photos/', verbose_name='Картинка детали')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_spareparts', to='spareparts.spareparts', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Картинка Детали',
                'verbose_name_plural': 'Картинки Детали',
            },
        ),
        migrations.CreateModel(
            name='VideoSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.URLField(blank=True, help_text='Введите ссылку на видео детали', null=True, verbose_name='Ссылка на видео детали')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_spareparts', to='spareparts.spareparts', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Видео Детали',
                'verbose_name_plural': 'Видео Детали',
            },
        ),
    ]
