# Generated by Django 5.0.1 on 2024-02-12 16:16

import apps.spareparts.models
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesparepart',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Загрузите изображение детали', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to=apps.spareparts.models.upload_to, verbose_name='Картинка детали'),
        ),
        migrations.AlterField(
            model_name='spareparts',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', help_text='Загрузите изображение детали', keep_meta=True, null=True, quality=85, scale=0.5, size=[800, 600], upload_to=apps.spareparts.models.upload_to, verbose_name='Картинка детали'),
        ),
    ]
